apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-msa-ui
  labels:
    app: ui-msa  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-msa
  template:
    metadata:
      labels:
        app: ui-msa
    spec:
      containers:
      - name: ui-msa
        image: nayoungjang/cicd-edu-msa-ui:18
        imagePullPolicy: Always
        ports:
        - containerPort: 28080           
---
apiVersion: v1
kind: Service
metadata:
  name: edu-msa-ui
  labels:
    app: ui-msa  
spec:
  ports:
  - nodePort: 33001
    port: 28080
    protocol: TCP
    targetPort: 28080
  selector:
    app: ui-msa
  type: NodePort
